import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/custom/Auth/auth-context";
import { AuthDialogProvider } from "@/components/custom/Auth/auth-dialog-context";
import { AuthDialog } from "@/components/custom/Auth/auth-dialog";
import Provider from "@/lib/providers/react-query/react-query.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthDialogProvider>
            <AuthDialog />
            <Provider>{children}</Provider>
          </AuthDialogProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
